### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by justynath** [justynath/harmony-hackers#1]
Wireframes for each of the pages and elements especially the landing page

**Comment by alanjameschapman** [comment]
Discussed various ideas with @hannahro15 on 18/09 PM after KO mtg.:
- Flashcard above/beside keyboard will display single note on stave for user to play on keyboard, followed by right/wrong feedback.
- Keyboard will be two octaves (25 notes) to enable user to play any scale or arpeggio single octave.

**Comment by alanjameschapman** [comment]
| Mobile | Tablet |
| - | - |
| ![Image](https://github.com/user-attachments/assets/ef231f02-00ad-4d1b-87ef-620393e85db8) | ![Image](https://github.com/user-attachments/assets/174acdb7-5673-48fd-8c8a-fd02a56951b5) |

**Comment by alanjameschapman** [comment]
| Page | Mobile | Desktop
| - | - | - |
Home | ![Image](https://github.com/user-attachments/assets/376543d6-a1c7-4da8-9a69-a450e1e23211) | ![Image](https://github.com/user-attachments/assets/c1f98140-1cd0-4a06-958a-a25b14b7293f)
Lesson | ![Image](https://github.com/user-attachments/assets/8f104452-9c58-46f7-8259-1da4a4d2c2df) | ![Image](https://github.com/user-attachments/assets/a78dab97-a360-459e-b1bc-20f217ba5ea3)
About | ![Image](https://github.com/user-attachments/assets/963128f5-1a7d-421f-b476-d96d70a91ec3) | ![Image](https://github.com/user-attachments/assets/94a0dd8b-1ee7-4576-aa61-e6f07995f7ce)
Contact | ![Image](https://github.com/user-attachments/assets/959891cd-4a79-4771-a80f-371c7b590087) | ![Image](https://github.com/user-attachments/assets/38e0d0e3-38e7-459e-9c80-35137f2786fc)
