### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by VCGithubCode** [justynath/harmony-hackers#5]

**Comment by alanjameschapman** [comment]
Mockups created for mobile device home page, to set the tone for members working on styling separate pages:

![Image](https://github.com/user-attachments/assets/61d81266-ec2b-43b9-996a-d57a67dd7d67)

**Comment by alanjameschapman** [comment]
| Page | Mobile | Desktop |
| - | - | - |
Home | ![Image](https://github.com/user-attachments/assets/f8bbe759-e0f8-4341-bf70-e64ad04f4d52) | ![Image](https://github.com/user-attachments/assets/d75562b9-12f0-4275-9527-06d7ef1b6369)
Lesson | ![Image](https://github.com/user-attachments/assets/82613eaf-8856-4524-b1f5-ae7e1fc4fc36) | ![Image](https://github.com/user-attachments/assets/a6ef7798-995f-4356-b72c-d3d0a2d4cdb8)
About | ![Image](https://github.com/user-attachments/assets/d4ece8ad-106f-401f-8d3e-fd2a3cbcb772) | ![Image](https://github.com/user-attachments/assets/a26312bc-828d-4825-900d-c6b467ea50cf)
Contact | ![Image](https://github.com/user-attachments/assets/e7b9c8f3-5cd4-483f-af9b-3cf03ab5b3a2) | ![Image](https://github.com/user-attachments/assets/eb6b5d6a-5258-41c0-bed6-5f5a2647a981)
